apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  labels:
    name: "bank-account-info-service"
    app: "banking-system"
  name: "bank-account-info-service"
spec:
  replicas: 1
  selector:
    matchLabels:
      name: "bank-account-info-service"
      app: "banking-system"
  template:
    metadata:
      labels:
        name: "bank-account-info-service"
        app: "banking-system"
    spec:
      containers:
      - name: "bank-account-info-service"
        image: "prithwi8972/bank-accountinfo-service:1.0.0"
        resources:
          limits:
            memory: "900Mi"
            cpu: "400m"
          requests:
            memory: "700Mi"
            cpu: "300m"
        ports:
        - containerPort: 8092
        env:
        - name: "DB_HOST"
          valueFrom:
            configMapKeyRef:
              name: "mysql-cm"
              key: "hostname"
        - name: "EUREKA_SERVER_ADDRESS"
          valueFrom:
            configMapKeyRef:
              name: "eureka-cm"
              key: "eureka_service_address"
---
apiVersion: "v1"
kind: "Service"
metadata:
  name: "bank-account-info-service"
spec:
  selector:
    name: "bank-account-info-service"
    app: "banking-system"
  ports:
  - port: 8092
    targetPort: 8092
---
apiVersion: "v1"
kind: "ConfigMap"
metadata:
  name: "eureka-cm"
data:
  eureka_service_address: "http://service-registry-deploy-0.service-registry-deploy.default.svc.cluster.local:8085/eureka"
---
apiVersion: "v1"
kind: "ConfigMap"
metadata:
  name: "mysql-cm"
data:
  hostname: "bankdb-0.bankdb"