spring:
  application:
    name: BANK-BRANCH-DETAILS
  datasource:
    url: jdbc:mysql://localhost:3306/bank_data
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver


  main:
    allow-circular-references: true
eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8085/eureka

management:
  endpoint:
    health:
      probes:
        enabled: true

server:
  port: 8091